# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\s\Desktop\register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import test_rc,re
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-image: url(:/newPrefix/tourism kiosk/penang tour.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 60, 381, 461))
        self.frame.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:0, stop:0.511364 rgba(0, 156, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 60px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.welcomeLabel = QtWidgets.QLabel(self.frame)
        self.welcomeLabel.setGeometry(QtCore.QRect(20, 10, 231, 101))
        self.welcomeLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.usernameEntry = QtWidgets.QLineEdit(self.frame)
        self.usernameEntry.setGeometry(QtCore.QRect(40, 140, 301, 41))
        self.usernameEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Arial\";\n"
"border-radius: 20px;\n"
"")
        self.usernameEntry.setText("")
        self.usernameEntry.setObjectName("usernameEntry")
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(130, 320, 111, 51))
        self.loginButton.setStyleSheet("/* Set the button\'s style */\n"
"QPushButton {\n"
"    background-color: rgb(88, 145, 167); \n"
"    font: 14pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* Change the cursor when hovering */\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 132);\n"
"    cursor: pointer; /* Change cursor to a pointing hand */\n"
"}\n"
"\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.usernameLabel = QtWidgets.QLabel(self.frame)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 110, 121, 21))
        self.usernameLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.frame)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 220, 121, 21))
        self.passwordLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.passwordLabel.setObjectName("passwordLabel")
        self.forgetPasswordButton = QtWidgets.QPushButton(self.frame)
        self.forgetPasswordButton.setGeometry(QtCore.QRect(250, 290, 91, 21))
        self.forgetPasswordButton.setStyleSheet("/* Set the button\'s style */\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color:rgb(0, 0, 0) ;\n"
"}\n"
"\n"
"/* Change the cursor when hovering */\n"
"QPushButton:hover {    \n"
"    color:rgb(255, 0, 0) ;\n"
"    cursor: pointer; /* Change cursor to a pointing hand */\n"
"}\n"
"")
        self.forgetPasswordButton.setObjectName("forgetPasswordButton")
        self.passwordEntry = QtWidgets.QLineEdit(self.frame)
        self.passwordEntry.setGeometry(QtCore.QRect(40, 250, 301, 41))
        self.passwordEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Arial\";\n"
"border-radius: 20px;\n"
"")
        self.passwordEntry.setText("")
        self.passwordEntry.setObjectName("passwordEntry")
        self.errorMessageLabel = QtWidgets.QLabel(self.frame)
        self.errorMessageLabel.setGeometry(QtCore.QRect(40, 380, 300, 31))
        self.errorMessageLabel.setStyleSheet("background-color: transparent;\n"
                                             "color: rgb(255, 0, 0);\n"
                                             "font: 10pt \"Arial Rounded MT Bold\";")
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        # Center-align the text
        self.errorMessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registrationButton = QtWidgets.QPushButton(self.frame)
        self.registrationButton.setGeometry(QtCore.QRect(90, 410, 191, 31))
        self.registrationButton.setStyleSheet("/* Set the button\'s style */\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    font: 14pt \"Arial\";\n"
"    color:rgb(0, 0, 0) ;\n"
"}\n"
"\n"
"/* Change the cursor when hovering */\n"
"QPushButton:hover {    \n"
"    color:rgb(255, 0, 0) ;\n"
"    cursor: pointer; /* Change cursor to a pointing hand */\n"
"}\n"
"")
        self.registrationButton.setObjectName("registrationButton")
        self.showPasswordButton = QtWidgets.QPushButton(self.frame)
        self.showPasswordButton.setGeometry(QtCore.QRect(280, 250, 51, 41))
        self.showPasswordButton.setStyleSheet("/* Set the button\'s style */\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Change the cursor when hovering */\n"
"QPushButton:pressed {\n"
"    ;\n"
"}\n"
"\n"
"\n"
"")
        self.showPasswordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showPasswordButton.setIcon(icon)
        self.showPasswordButton.setIconSize(QtCore.QSize(35, 35))
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.passwordEntry.raise_()
        self.welcomeLabel.raise_()
        self.usernameEntry.raise_()
        self.loginButton.raise_()
        self.usernameLabel.raise_()
        self.passwordLabel.raise_()
        self.forgetPasswordButton.raise_()
        self.errorMessageLabel.raise_()
        self.registrationButton.raise_()
        self.showPasswordButton.raise_()
        self.penangimg = QtWidgets.QPushButton(self.centralwidget)
        self.penangimg.setGeometry(QtCore.QRect(810, 470, 201, 101))
        self.penangimg.setStyleSheet("background-color: transparent;")
        self.penangimg.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/letstravel.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.penangimg.setIcon(icon2)
        self.penangimg.setIconSize(QtCore.QSize(200, 200))
        self.penangimg.setObjectName("penangimg")
        self.planeimg = QtWidgets.QPushButton(self.centralwidget)
        self.planeimg.setGeometry(QtCore.QRect(830, 30, 171, 101))
        self.planeimg.setStyleSheet("background-color: transparent;")
        self.planeimg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/travelplane.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.planeimg.setIcon(icon1)
        self.planeimg.setIconSize(QtCore.QSize(150, 150))
        self.planeimg.setObjectName("planeimg")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Hi, Welcome !</span></p></body></html>"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.usernameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Username</span></p></body></html>"))
        self.passwordLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Password</span></p></body></html>"))
        self.forgetPasswordButton.setText(_translate("MainWindow", "Forget password?"))
        self.errorMessageLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.registrationButton.setText(_translate("MainWindow", "Register an account"))
        # Connect the showPasswordButton's clicked signal to the toggleShowPassword method
        self.showPasswordButton.clicked.connect(self.toggleShowPassword)

    def toggleShowPassword(self):
        # Toggle the password visibility when the button is clicked
        is_password_visible = self.passwordEntry.echoMode() == QtWidgets.QLineEdit.Normal

        if is_password_visible:
            # Change the icon and set the password mode to Password
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.showPasswordButton.setIcon(icon)
            self.passwordEntry.setEchoMode(QtWidgets.QLineEdit.Password)
        else:
            # Change the icon and set the password mode to Normal
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.showPasswordButton.setIcon(icon)
            self.passwordEntry.setEchoMode(QtWidgets.QLineEdit.Normal)



class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(1020, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegistrationWindow.sizePolicy().hasHeightForWidth())
        RegistrationWindow.setSizePolicy(sizePolicy)
        RegistrationWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(RegistrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-image: url(:/newPrefix/tourism kiosk/penang tour.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 60, 381, 461))
        self.frame.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:0, stop:0.511364 rgba(0, 156, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 60px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.emailEntry = QtWidgets.QLineEdit(self.frame)
        self.emailEntry.setGeometry(QtCore.QRect(40, 140, 301, 31))
        self.emailEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Arial\";\n"
"border-radius: 11px;\n"
"")
        self.emailEntry.setText("")
        self.emailEntry.setObjectName("emailEntry")
        self.signupButton = QtWidgets.QPushButton(self.frame)
        self.signupButton.setGeometry(QtCore.QRect(130, 350, 111, 51))
        self.signupButton.setStyleSheet("/* Set the button\'s style */\n"
"QPushButton {\n"
"    background-color: rgb(88, 145, 167); \n"
"    font: 14pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* Change the cursor when hovering */\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 132);\n"
"    cursor: pointer; /* Change cursor to a pointing hand */\n"
"}\n"
"\n"
"")
        self.signupButton.setObjectName("signupButton")
        self.usernameLabel = QtWidgets.QLabel(self.frame)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 30, 111, 31))
        self.usernameLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.frame)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 190, 111, 21))
        self.passwordLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.passwordLabel.setObjectName("passwordLabel")
        self.errorMessageLabel = QtWidgets.QLabel(self.frame)
        self.errorMessageLabel.setGeometry(QtCore.QRect(30, 410, 320, 31))
        self.errorMessageLabel.setStyleSheet("background-color: transparent;\n"
                                             "color: rgb(255, 0, 0);\n"
                                             "font: 10pt \"Arial Rounded MT Bold\";")
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        # Center-align the text
        self.errorMessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emailLabel = QtWidgets.QLabel(self.frame)
        self.emailLabel.setGeometry(QtCore.QRect(30, 110, 91, 31))
        self.emailLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.emailLabel.setObjectName("emailLabel")
        self.usernameEntry = QtWidgets.QLineEdit(self.frame)
        self.usernameEntry.setGeometry(QtCore.QRect(40, 60, 301, 31))
        self.usernameEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Arial\";\n"
"border-radius: 11px;\n"
"")
        self.usernameEntry.setText("")
        self.usernameEntry.setObjectName("usernameEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.frame)
        self.passwordEntry.setGeometry(QtCore.QRect(40, 220, 301, 31))
        self.passwordEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Arial\";\n"
"border-radius: 11px;\n"
"")
        self.passwordEntry.setText("")
        self.passwordEntry.setObjectName("passwordEntry")
        self.cityLabel = QtWidgets.QLabel(self.frame)
        self.cityLabel.setGeometry(QtCore.QRect(30, 270, 71, 21))
        self.cityLabel.setStyleSheet("background-color: transparent;\n"
"font: 16pt \"Arial Rounded MT Bold\";")
        self.cityLabel.setObjectName("cityLabel")
        self.cityEntry = QtWidgets.QLineEdit(self.frame)
        self.cityEntry.setGeometry(QtCore.QRect(40, 300, 301, 31))
        self.cityEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Arial\";\n"
"border-radius: 11px;\n"
"")
        self.cityEntry.setText("")
        self.cityEntry.setObjectName("cityEntry")
        self.planeimg = QtWidgets.QPushButton(self.centralwidget)
        self.planeimg.setGeometry(QtCore.QRect(830, 30, 171, 101))
        self.planeimg.setStyleSheet("background-color: transparent;")
        self.planeimg.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/travelplane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.planeimg.setIcon(icon)
        self.planeimg.setIconSize(QtCore.QSize(150, 150))
        self.planeimg.setObjectName("planeimg")
        self.penangimg = QtWidgets.QPushButton(self.centralwidget)
        self.penangimg.setGeometry(QtCore.QRect(810, 470, 201, 101))
        self.penangimg.setStyleSheet("background-color: transparent;")
        self.penangimg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/letstravel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penangimg.setIcon(icon1)
        self.penangimg.setIconSize(QtCore.QSize(200, 200))
        self.penangimg.setObjectName("penangimg")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(40, 20, 51, 51))
        self.backButton.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"/* Change the cursor when hovering */\n"
"QPushButton:hover {\n"
"    background-color:rgb(0, 0, 127);\n"
"    cursor: pointer; /* Change cursor to a pointing hand */\n"
"}\n"
"")
        self.backButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\tourism kiosk/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon2)
        self.backButton.setIconSize(QtCore.QSize(50, 50))
        self.backButton.setObjectName("backButton")
        RegistrationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "RegistrationWindow"))
        self.signupButton.setText(_translate("RegistrationWindow", "Signup"))
        self.usernameLabel.setText(_translate("RegistrationWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Username</span></p></body></html>"))
        self.passwordLabel.setText(_translate("RegistrationWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Password</span></p></body></html>"))
        self.errorMessageLabel.setText(_translate("RegistrationWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.emailLabel.setText(_translate("RegistrationWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Email</span></p></body></html>"))
        self.cityLabel.setText(_translate("RegistrationWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">City</span></p></body></html>"))

class LoginWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Connect the login button to the login function
        self.ui.loginButton.clicked.connect(self.login)

        # Connect the registration button to show the registration window
        self.ui.registrationButton.clicked.connect(self.show_registration_window)

    def login(self):
        # Implement your login logic here
        # You can access the entered username and password like this:
        username = self.ui.usernameEntry.text()
        password = self.ui.passwordEntry.text()

        # Placeholder logic - show an error message if fields are empty
        if not username or not password:
            self.ui.errorMessageLabel.setText("Please enter both username and password.")
        elif username == "admin" and password == "admin":
            # Placeholder: successful login
            self.ui.errorMessageLabel.setText("")
        else:
            self.ui.errorMessageLabel.setText("Invalid username or password")

    def show_registration_window(self):
        self.registration_window = RegistrationWindow()
        self.registration_window.ui.backButton.clicked.connect(self.show_login_window)
        self.registration_window.show()
        self.hide()

    def show_login_window(self):
        self.show()
        self.registration_window.close()

class RegistrationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_RegistrationWindow()
        self.ui.setupUi(self)

        # Connect the signup button to the registration function
        self.ui.signupButton.clicked.connect(self.register)

    def register(self):
        # Access user input
        username = self.ui.usernameEntry.text()
        password = self.ui.passwordEntry.text()
        email = self.ui.emailEntry.text()
        city = self.ui.cityEntry.text()

        # Validate inputs
        if not username or not password or not email or not city:
            self.ui.errorMessageLabel.setText("Please fill in all the fields.")
        elif not re.match(r"[^@\s]+@[^@\s]+\.[a-zA-Z0-9]+$", email):
            self.ui.errorMessageLabel.setText("Invalid email address.")
        elif len(password) <= 8:
            self.ui.errorMessageLabel.setText("Password must be longer than 8 characters.")
        elif username_exists(username):
            self.ui.errorMessageLabel.setText("Username already exists.")
        elif email_exists(email):
            self.ui.errorMessageLabel.setText("Email already registered.")
        else:
            # Perform the actual registration process
            if self.perform_registration(username, password, email,city):
                self.ui.errorMessageLabel.setText("Registration successful!")
            else:
                self.ui.errorMessageLabel.setText("Registration failed. Please try again later.")

    def username_exists(username):
        # Check if the username already exists in the database
        pass

    def email_exists(email):
        # Check if the email address already exists in the database
        pass

    def perform_registration(username, password, email, city):
        # Implement the actual registration process (e.g., insert data into the database)
        # Return True if registration is successful, False otherwise
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = LoginWindow()
    login_window.show()
    sys.exit(app.exec_())
