# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1364, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_label_1 = QtWidgets.QLabel(self.icon_only_widget)
        self.logo_label_1.setMinimumSize(QtCore.QSize(50, 50))
        self.logo_label_1.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_label_1.setStyleSheet("")
        self.logo_label_1.setText("")
        self.logo_label_1.setScaledContents(True)
        self.logo_label_1.setObjectName("logo_label_1")
        self.horizontalLayout_3.addWidget(self.logo_label_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 30, -1, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attraction_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.attraction_btn_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("attraction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attraction_btn_1.setIcon(icon)
        self.attraction_btn_1.setCheckable(True)
        self.attraction_btn_1.setAutoExclusive(True)
        self.attraction_btn_1.setObjectName("attraction_btn_1")
        self.verticalLayout.addWidget(self.attraction_btn_1)
        self.profile_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.profile_btn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_btn_1.setIcon(icon1)
        self.profile_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.profile_btn_1.setCheckable(True)
        self.profile_btn_1.setAutoExclusive(True)
        self.profile_btn_1.setObjectName("profile_btn_1")
        self.verticalLayout.addWidget(self.profile_btn_1)
        self.history_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.history_btn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("favourite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_btn_1.setIcon(icon2)
        self.history_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.history_btn_1.setCheckable(True)
        self.history_btn_1.setAutoExclusive(True)
        self.history_btn_1.setObjectName("history_btn_1")
        self.verticalLayout.addWidget(self.history_btn_1)
        self.booking_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.booking_btn_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("booking.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.booking_btn_1.setIcon(icon3)
        self.booking_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.booking_btn_1.setCheckable(True)
        self.booking_btn_1.setAutoExclusive(True)
        self.booking_btn_1.setObjectName("booking_btn_1")
        self.verticalLayout.addWidget(self.booking_btn_1)
        self.deals_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.deals_btn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("deal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deals_btn_1.setIcon(icon4)
        self.deals_btn_1.setCheckable(True)
        self.deals_btn_1.setAutoExclusive(True)
        self.deals_btn_1.setObjectName("deals_btn_1")
        self.verticalLayout.addWidget(self.deals_btn_1)
        self.chatbot_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.chatbot_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("cus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatbot_btn_1.setIcon(icon5)
        self.chatbot_btn_1.setCheckable(True)
        self.chatbot_btn_1.setAutoExclusive(True)
        self.chatbot_btn_1.setObjectName("chatbot_btn_1")
        self.verticalLayout.addWidget(self.chatbot_btn_1)
        self.feedback_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.feedback_btn_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("feedback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_btn_1.setIcon(icon6)
        self.feedback_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.feedback_btn_1.setCheckable(True)
        self.feedback_btn_1.setAutoExclusive(True)
        self.feedback_btn_1.setObjectName("feedback_btn_1")
        self.verticalLayout.addWidget(self.feedback_btn_1)
        self.map_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.map_btn_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.map_btn_1.setIcon(icon7)
        self.map_btn_1.setCheckable(True)
        self.map_btn_1.setAutoExclusive(True)
        self.map_btn_1.setObjectName("map_btn_1")
        self.verticalLayout.addWidget(self.map_btn_1)
        self.quiz_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.quiz_btn_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("game.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quiz_btn_1.setIcon(icon8)
        self.quiz_btn_1.setCheckable(True)
        self.quiz_btn_1.setAutoExclusive(True)
        self.quiz_btn_1.setObjectName("quiz_btn_1")
        self.verticalLayout.addWidget(self.quiz_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("exit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(icon9)
        self.exit_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setStyleSheet("gridline-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_2.setMinimumSize(QtCore.QSize(80, 40))
        self.logo_label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setText("")
        self.logo_label_2.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo_label_2.setScaledContents(True)
        self.logo_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout_2.addWidget(self.logo_label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, 30, -1, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.attraction_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(8)
        self.attraction_btn_2.setFont(font)
        self.attraction_btn_2.setCheckable(True)
        self.attraction_btn_2.setAutoExclusive(True)
        self.attraction_btn_2.setObjectName("attraction_btn_2")
        self.verticalLayout_2.addWidget(self.attraction_btn_2)
        self.profile_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_btn_2.sizePolicy().hasHeightForWidth())
        self.profile_btn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.profile_btn_2.setFont(font)
        self.profile_btn_2.setMouseTracking(False)
        self.profile_btn_2.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.profile_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.profile_btn_2.setCheckable(True)
        self.profile_btn_2.setAutoExclusive(True)
        self.profile_btn_2.setObjectName("profile_btn_2")
        self.verticalLayout_2.addWidget(self.profile_btn_2)
        self.history_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.history_btn_2.setFont(font)
        self.history_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.history_btn_2.setCheckable(True)
        self.history_btn_2.setAutoExclusive(True)
        self.history_btn_2.setObjectName("history_btn_2")
        self.verticalLayout_2.addWidget(self.history_btn_2)
        self.booking_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.booking_btn_2.setFont(font)
        self.booking_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.booking_btn_2.setCheckable(True)
        self.booking_btn_2.setAutoExclusive(True)
        self.booking_btn_2.setObjectName("booking_btn_2")
        self.verticalLayout_2.addWidget(self.booking_btn_2)
        self.deal_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.deal_btn_2.setFont(font)
        self.deal_btn_2.setCheckable(True)
        self.deal_btn_2.setAutoExclusive(True)
        self.deal_btn_2.setObjectName("deal_btn_2")
        self.verticalLayout_2.addWidget(self.deal_btn_2)
        self.chatbot_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.chatbot_btn_2.setFont(font)
        self.chatbot_btn_2.setCheckable(True)
        self.chatbot_btn_2.setAutoExclusive(True)
        self.chatbot_btn_2.setObjectName("chatbot_btn_2")
        self.verticalLayout_2.addWidget(self.chatbot_btn_2)
        self.feedback_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.feedback_btn_2.setFont(font)
        self.feedback_btn_2.setCheckable(True)
        self.feedback_btn_2.setAutoExclusive(True)
        self.feedback_btn_2.setObjectName("feedback_btn_2")
        self.verticalLayout_2.addWidget(self.feedback_btn_2)
        self.map_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setBold(False)
        font.setWeight(50)
        self.map_btn_2.setFont(font)
        self.map_btn_2.setCheckable(True)
        self.map_btn_2.setAutoExclusive(True)
        self.map_btn_2.setObjectName("map_btn_2")
        self.verticalLayout_2.addWidget(self.map_btn_2)
        self.quiz_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.quiz_btn_2.setFont(font)
        self.quiz_btn_2.setCheckable(True)
        self.quiz_btn_2.setAutoExclusive(True)
        self.quiz_btn_2.setObjectName("quiz_btn_2")
        self.verticalLayout_2.addWidget(self.quiz_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(-70, 0, 1222, 3022))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setMinimumSize(QtCore.QSize(1200, 3000))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.search_btn_3 = QtWidgets.QPushButton(self.frame_2)
        self.search_btn_3.setGeometry(QtCore.QRect(840, 0, 31, 31))
        self.search_btn_3.setStyleSheet("\n"
                                        "background-color: rgb(255, 255, 255);")
        self.search_btn_3.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("serach1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn_3.setIcon(icon11)
        self.search_btn_3.setObjectName("search_btn_3")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setStyleSheet("\n"
"background-color: rgb(228, 242, 253);\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_btn = QtWidgets.QPushButton(self.widget)
        self.change_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.change_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("navigationmanual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon10)
        self.change_btn.setIconSize(QtCore.QSize(20, 20))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn)
        spacerItem2 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setStyleSheet("\n"
"background-color: rgb(228, 242, 253);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.page_8)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1222, 3022))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.profile_frame_left = QtWidgets.QFrame(self.page_1)
        self.profile_frame_left.setFrameShape(QtWidgets.QFrame.Box)
        self.profile_frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_frame_left.setObjectName("profile_frame_left")
        self.profile_logo = QtWidgets.QLabel(self.profile_frame_left)
        self.profile_logo.setGeometry(QtCore.QRect(120, 40, 111, 111))
        self.profile_logo.setText("")
        self.profile_logo.setPixmap(QtGui.QPixmap("profile 2(1).png"))
        self.profile_logo.setObjectName("profile_logo")
        self.username = QtWidgets.QLabel(self.profile_frame_left)
        self.username.setGeometry(QtCore.QRect(120, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.gridLayout_2.addWidget(self.profile_frame_left, 0, 0, 1, 1)
        self.profile_frame_middle = QtWidgets.QFrame(self.page_1)
        self.profile_frame_middle.setFrameShape(QtWidgets.QFrame.Box)
        self.profile_frame_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_frame_middle.setObjectName("profile_frame_middle")
        self.ProfileSetting = QtWidgets.QLabel(self.profile_frame_middle)
        self.ProfileSetting.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(15)
        self.ProfileSetting.setFont(font)
        self.ProfileSetting.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ProfileSetting.setObjectName("ProfileSetting")
        self.FirstName_input = QtWidgets.QLineEdit(self.profile_frame_middle)
        self.FirstName_input.setGeometry(QtCore.QRect(20, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FirstName_input.setFont(font)
        self.FirstName_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.FirstName_input.setObjectName("FirstName_input")
        self.LastName_input = QtWidgets.QLineEdit(self.profile_frame_middle)
        self.LastName_input.setGeometry(QtCore.QRect(190, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LastName_input.setFont(font)
        self.LastName_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.LastName_input.setObjectName("LastName_input")
        self.MobileNumber_input = QtWidgets.QLineEdit(self.profile_frame_middle)
        self.MobileNumber_input.setGeometry(QtCore.QRect(20, 180, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MobileNumber_input.setFont(font)
        self.MobileNumber_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.MobileNumber_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.MobileNumber_input.setObjectName("MobileNumber_input")
        self.Address1_input = QtWidgets.QLineEdit(self.profile_frame_middle)
        self.Address1_input.setGeometry(QtCore.QRect(20, 280, 341, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Address1_input.setFont(font)
        self.Address1_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.Address1_input.setText("")
        self.Address1_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Address1_input.setObjectName("Address1_input")
        self.postcode_input = QtWidgets.QLineEdit(self.profile_frame_middle)
        self.postcode_input.setGeometry(QtCore.QRect(20, 460, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.postcode_input.setFont(font)
        self.postcode_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.postcode_input.setText("")
        self.postcode_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.postcode_input.setObjectName("postcode_input")
        self.Area_input = QtWidgets.QLineEdit(self.profile_frame_middle)
        self.Area_input.setGeometry(QtCore.QRect(20, 580, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Area_input.setFont(font)
        self.Area_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.Area_input.setText("")
        self.Area_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Area_input.setObjectName("Area_input")
        self.FirstName = QtWidgets.QLabel(self.profile_frame_middle)
        self.FirstName.setGeometry(QtCore.QRect(20, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FirstName.setFont(font)
        self.FirstName.setObjectName("FirstName")
        self.LastName = QtWidgets.QLabel(self.profile_frame_middle)
        self.LastName.setGeometry(QtCore.QRect(190, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LastName.setFont(font)
        self.LastName.setObjectName("LastName")
        self.MobileNumber = QtWidgets.QLabel(self.profile_frame_middle)
        self.MobileNumber.setGeometry(QtCore.QRect(20, 160, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MobileNumber.setFont(font)
        self.MobileNumber.setObjectName("MobileNumber")
        self.Address = QtWidgets.QLabel(self.profile_frame_middle)
        self.Address.setGeometry(QtCore.QRect(20, 260, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Address.setFont(font)
        self.Address.setObjectName("Address")
        self.Postcode = QtWidgets.QLabel(self.profile_frame_middle)
        self.Postcode.setGeometry(QtCore.QRect(20, 440, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Postcode.setFont(font)
        self.Postcode.setObjectName("Postcode")
        self.Area = QtWidgets.QLabel(self.profile_frame_middle)
        self.Area.setGeometry(QtCore.QRect(20, 560, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Area.setFont(font)
        self.Area.setObjectName("Area")
        self.gridLayout_2.addWidget(self.profile_frame_middle, 0, 2, 1, 1)
        self.profile_frame_right = QtWidgets.QFrame(self.page_1)
        self.profile_frame_right.setFrameShape(QtWidgets.QFrame.Box)
        self.profile_frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_frame_right.setObjectName("profile_frame_right")
        self.save_profile_button = QtWidgets.QPushButton(self.profile_frame_right)
        self.save_profile_button.setGeometry(QtCore.QRect(140, 590, 93, 28))
        self.save_profile_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.save_profile_button.setObjectName("save_profile_button")
        self.DateOfBirth = QtWidgets.QLabel(self.profile_frame_right)
        self.DateOfBirth.setGeometry(QtCore.QRect(40, 90, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DateOfBirth.setFont(font)
        self.DateOfBirth.setObjectName("DateOfBirth")
        self.dateEdit = QtWidgets.QDateEdit(self.profile_frame_right)
        self.dateEdit.setGeometry(QtCore.QRect(40, 110, 131, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.Gender = QtWidgets.QLabel(self.profile_frame_right)
        self.Gender.setGeometry(QtCore.QRect(40, 230, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Gender.setFont(font)
        self.Gender.setObjectName("Gender")
        self.male_checkBox = QtWidgets.QCheckBox(self.profile_frame_right)
        self.male_checkBox.setGeometry(QtCore.QRect(40, 260, 81, 20))
        self.male_checkBox.setObjectName("male_checkBox")
        self.female_checkBox = QtWidgets.QCheckBox(self.profile_frame_right)
        self.female_checkBox.setGeometry(QtCore.QRect(40, 300, 81, 20))
        self.female_checkBox.setObjectName("female_checkBox")
        self.gridLayout_2.addWidget(self.profile_frame_right, 0, 3, 1, 1)
        self.profile_frame_middle.raise_()
        self.profile_frame_left.raise_()
        self.profile_frame_right.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.historypage = QtWidgets.QScrollArea(self.page_3)
        self.historypage.setWidgetResizable(True)
        self.historypage.setObjectName("historypage")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1150, 1222))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 1200))
        self.frame.setStyleSheet("\n"
"background-color: rgb(228, 242, 253);\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setGeometry(QtCore.QRect(40, 90, 971, 192))
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(4, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(5, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(6, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(7, font)
        self.history_label = QtWidgets.QLabel(self.frame)
        self.history_label.setGeometry(QtCore.QRect(40, 10, 301, 71))
        self.history_label.setStyleSheet("font: 87 20pt \"Arial Black\";")
        self.history_label.setObjectName("history_label")
        self.verticalLayout_6.addWidget(self.frame)
        self.historypage.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.historypage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1222, 3022))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bookingpage = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.bookingpage.setMinimumSize(QtCore.QSize(1200, 3000))
        self.bookingpage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bookingpage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bookingpage.setObjectName("bookingpage")





        self.booking_label = QtWidgets.QLabel(self.bookingpage)
        self.booking_label.setGeometry(QtCore.QRect(20, 120, 1161, 351))
        self.booking_label.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_label.setText("")
        self.booking_label.setObjectName("booking_label")
        self.booking_pic = QtWidgets.QLabel(self.bookingpage)
        self.booking_pic.setGeometry(QtCore.QRect(30, 130, 291, 331))
        self.booking_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic.setText("")
        self.booking_pic.setObjectName("booking_pic")
        self.book_btn = QtWidgets.QPushButton(self.bookingpage)
        self.book_btn.setGeometry(QtCore.QRect(1040, 430, 121, 28))
        self.book_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.book_btn.setObjectName("book_btn")
        self.bookingtitle = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingtitle.setGeometry(QtCore.QRect(340, 130, 831, 41))
        self.bookingtitle.setObjectName("bookingtitle")
        self.booking_price = QtWidgets.QTextEdit(self.bookingpage)
        self.booking_price.setGeometry(QtCore.QRect(890, 430, 131, 31))
        self.booking_price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.booking_price.setObjectName("booking_price")
        self.bookingdescription = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingdescription.setGeometry(QtCore.QRect(340, 190, 831, 231))
        self.bookingdescription.setObjectName("bookingdescription")
        self.booking_label_3 = QtWidgets.QLabel(self.bookingpage)
        self.booking_label_3.setGeometry(QtCore.QRect(20, 550, 1161, 351))
        self.booking_label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_label_3.setText("")
        self.booking_label_3.setObjectName("booking_label_3")
        self.booking_label_4 = QtWidgets.QLabel(self.bookingpage)
        self.booking_label_4.setGeometry(QtCore.QRect(20, 980, 1161, 351))
        self.booking_label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_label_4.setText("")
        self.booking_label_4.setObjectName("booking_label_4")
        self.booking_label_5 = QtWidgets.QLabel(self.bookingpage)
        self.booking_label_5.setGeometry(QtCore.QRect(20, 1400, 1161, 351))
        self.booking_label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_label_5.setText("")
        self.booking_label_5.setObjectName("booking_label_5")
        self.booking_label_6 = QtWidgets.QLabel(self.bookingpage)
        self.booking_label_6.setGeometry(QtCore.QRect(20, 1820, 1161, 351))
        self.booking_label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_label_6.setText("")
        self.booking_label_6.setObjectName("booking_label_6")
        self.booking_pic_7 = QtWidgets.QLabel(self.bookingpage)
        self.booking_pic_7.setGeometry(QtCore.QRect(30, 560, 291, 331))
        self.booking_pic_7.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_7.setText("")
        self.booking_pic_7.setObjectName("booking_pic_7")
        self.booking_pic_8 = QtWidgets.QLabel(self.bookingpage)
        self.booking_pic_8.setGeometry(QtCore.QRect(30, 990, 291, 331))
        self.booking_pic_8.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_8.setText("")
        self.booking_pic_8.setObjectName("booking_pic_8")
        self.booking_pic_9 = QtWidgets.QLabel(self.bookingpage)
        self.booking_pic_9.setGeometry(QtCore.QRect(30, 1410, 291, 331))
        self.booking_pic_9.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_9.setText("")
        self.booking_pic_9.setObjectName("booking_pic_9")
        self.booking_pic_10 = QtWidgets.QLabel(self.bookingpage)
        self.booking_pic_10.setGeometry(QtCore.QRect(30, 1830, 291, 331))
        self.booking_pic_10.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_10.setText("")
        self.booking_pic_10.setObjectName("booking_pic_10")
        self.bookingtitle_2 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingtitle_2.setGeometry(QtCore.QRect(340, 570, 831, 41))
        self.bookingtitle_2.setObjectName("bookingtitle_2")
        self.bookingtitle_3 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingtitle_3.setGeometry(QtCore.QRect(340, 1000, 831, 41))
        self.bookingtitle_3.setObjectName("bookingtitle_3")
        self.bookingtitle_4 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingtitle_4.setGeometry(QtCore.QRect(340, 1420, 831, 41))
        self.bookingtitle_4.setObjectName("bookingtitle_4")
        self.bookingtitle_5 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingtitle_5.setGeometry(QtCore.QRect(340, 1840, 831, 41))
        self.bookingtitle_5.setObjectName("bookingtitle_5")
        self.bookingdescription_2 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingdescription_2.setGeometry(QtCore.QRect(340, 630, 831, 221))
        self.bookingdescription_2.setObjectName("bookingdescription_2")
        self.bookingdescription_3 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingdescription_3.setGeometry(QtCore.QRect(340, 1050, 831, 231))
        self.bookingdescription_3.setObjectName("bookingdescription_3")
        self.bookingdescription_4 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingdescription_4.setGeometry(QtCore.QRect(340, 1470, 831, 231))
        self.bookingdescription_4.setObjectName("bookingdescription_4")
        self.bookingdescription_5 = QtWidgets.QTextEdit(self.bookingpage)
        self.bookingdescription_5.setGeometry(QtCore.QRect(340, 1890, 831, 231))
        self.bookingdescription_5.setObjectName("bookingdescription_5")
        self.book_btn_2 = QtWidgets.QPushButton(self.bookingpage)
        self.book_btn_2.setGeometry(QtCore.QRect(1050, 860, 121, 28))
        self.book_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.book_btn_2.setObjectName("book_btn_2")
        self.book_btn_3 = QtWidgets.QPushButton(self.bookingpage)
        self.book_btn_3.setGeometry(QtCore.QRect(1050, 1290, 121, 28))
        self.book_btn_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.book_btn_3.setObjectName("book_btn_3")
        self.book_btn_4 = QtWidgets.QPushButton(self.bookingpage)
        self.book_btn_4.setGeometry(QtCore.QRect(1050, 1710, 121, 28))
        self.book_btn_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.book_btn_4.setObjectName("book_btn_4")
        self.book_btn_5 = QtWidgets.QPushButton(self.bookingpage)
        self.book_btn_5.setGeometry(QtCore.QRect(1050, 2130, 121, 28))
        self.book_btn_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.book_btn_5.setObjectName("book_btn_5")
        self.booking_price_3 = QtWidgets.QTextEdit(self.bookingpage)
        self.booking_price_3.setGeometry(QtCore.QRect(900, 860, 131, 31))
        self.booking_price_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.booking_price_3.setObjectName("booking_price_3")
        self.booking_price_4 = QtWidgets.QTextEdit(self.bookingpage)
        self.booking_price_4.setGeometry(QtCore.QRect(900, 1290, 131, 31))
        self.booking_price_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.booking_price_4.setObjectName("booking_price_4")
        self.booking_price_5 = QtWidgets.QTextEdit(self.bookingpage)
        self.booking_price_5.setGeometry(QtCore.QRect(900, 1710, 131, 31))
        self.booking_price_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.booking_price_5.setObjectName("booking_price_5")
        self.booking_price_6 = QtWidgets.QTextEdit(self.bookingpage)
        self.booking_price_6.setGeometry(QtCore.QRect(900, 2130, 131, 31))
        self.booking_price_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.booking_price_6.setObjectName("booking_price_6")
        self.horizontalLayout_6.addWidget(self.bookingpage)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.page_5)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1222, 3022))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dealspage = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.gridLayout_6.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.customerservicepage = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.customerservicepage.setFont(font)
        self.customerservicepage.setStyleSheet("\n"
"background-color: rgb(228, 242, 253);\n"
"")
        self.customerservicepage.setAlignment(QtCore.Qt.AlignCenter)
        self.customerservicepage.setObjectName("customerservicepage")
        self.gridLayout_7.addWidget(self.customerservicepage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.feedbackpage = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.feedbackpage.setFont(font)
        self.feedbackpage.setStyleSheet("\n"
"background-color: rgb(228, 242, 253);\n"
"")
        self.feedbackpage.setAlignment(QtCore.Qt.AlignCenter)
        self.feedbackpage.setObjectName("feedbackpage")
        self.gridLayout_8.addWidget(self.feedbackpage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.map_page = QtWidgets.QWidget()
        self.map_page.setObjectName("map_page")
        self.stackedWidget.addWidget(self.map_page)

        # Create a QWebEngineView widget and set its size and position
        self.webView = QWebEngineView(self.map_page)
        self.webView.setGeometry(QtCore.QRect(10, 10, 1200, 800))  # Adjust the size and position as needed
        self.webView.setObjectName("webView")

        # Load a web page into the QWebEngineView widget
        self.webView.setUrl(QtCore.QUrl("https://www.google.com/maps"))

        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_9)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1222, 1222))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_3.setMinimumSize(QtCore.QSize(1200, 1200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.bookingpage_2 = QtWidgets.QFrame(self.frame_3)
        self.bookingpage_2.setGeometry(QtCore.QRect(30, 30, 1200, 3600))
        self.bookingpage_2.setMinimumSize(QtCore.QSize(1200, 3600))
        self.bookingpage_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bookingpage_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bookingpage_2.setObjectName("bookingpage_2")


        self.checkin_input_2 = QtWidgets.QDateEdit(self.bookingpage_2)
        self.checkin_input_2.setGeometry(QtCore.QRect(610, 10, 201, 31))
        self.checkin_input_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkin_input_2.setObjectName("checkin_input_2")
        self.checkout_input_2 = QtWidgets.QDateEdit(self.bookingpage_2)
        self.checkout_input_2.setGeometry(QtCore.QRect(810, 10, 201, 31))
        self.checkout_input_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkout_input_2.setObjectName("checkout_input_2")

        self.booking_label_2 = QtWidgets.QLabel(self.bookingpage_2)
        self.booking_label_2.setGeometry(QtCore.QRect(0, 120, 1161, 571))
        self.booking_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_label_2.setText("")
        self.booking_label_2.setObjectName("booking_label_2")
        self.booking_pic_2 = QtWidgets.QLabel(self.bookingpage_2)
        self.booking_pic_2.setGeometry(QtCore.QRect(10, 230, 521, 451))
        self.booking_pic_2.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_2.setText("")
        self.booking_pic_2.setObjectName("booking_pic_2")
        self.label = QtWidgets.QLabel(self.bookingpage_2)
        self.label.setGeometry(QtCore.QRect(0, 710, 1161, 251))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.booking_pic_3 = QtWidgets.QLabel(self.bookingpage_2)
        self.booking_pic_3.setGeometry(QtCore.QRect(540, 230, 311, 221))
        self.booking_pic_3.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_3.setText("")
        self.booking_pic_3.setObjectName("booking_pic_3")
        self.booking_pic_4 = QtWidgets.QLabel(self.bookingpage_2)
        self.booking_pic_4.setGeometry(QtCore.QRect(540, 460, 311, 221))
        self.booking_pic_4.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_4.setText("")
        self.booking_pic_4.setObjectName("booking_pic_4")
        self.booking_pic_5 = QtWidgets.QLabel(self.bookingpage_2)
        self.booking_pic_5.setGeometry(QtCore.QRect(860, 230, 291, 221))
        self.booking_pic_5.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_5.setText("")
        self.booking_pic_5.setObjectName("booking_pic_5")
        self.booking_pic_6 = QtWidgets.QLabel(self.bookingpage_2)
        self.booking_pic_6.setGeometry(QtCore.QRect(860, 460, 291, 221))
        self.booking_pic_6.setFrameShape(QtWidgets.QFrame.Box)
        self.booking_pic_6.setText("")
        self.booking_pic_6.setObjectName("booking_pic_6")
        self.booking_title_2 = QtWidgets.QTextEdit(self.bookingpage_2)
        self.booking_title_2.setGeometry(QtCore.QRect(10, 130, 841, 61))
        self.booking_title_2.setObjectName("booking_title_2")
        self.booking_price_2 = QtWidgets.QTextEdit(self.bookingpage_2)
        self.booking_price_2.setGeometry(QtCore.QRect(960, 130, 171, 61))
        self.booking_price_2.setObjectName("booking_price_2")
        self.booking_description_2 = QtWidgets.QTextEdit(self.bookingpage_2)
        self.booking_description_2.setGeometry(QtCore.QRect(10, 720, 1141, 231))
        self.booking_description_2.setObjectName("booking_description_2")
        self.booking_btn = QtWidgets.QPushButton(self.bookingpage_2)
        self.booking_btn.setGeometry(QtCore.QRect(960, 1000, 191, 41))
        self.booking_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.booking_btn.setObjectName("booking_btn")
        self.comboBox = QtWidgets.QComboBox(self.bookingpage_2)
        self.comboBox.setGeometry(QtCore.QRect(780, 1000, 101, 41))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.back_booking = QtWidgets.QPushButton(self.bookingpage_2)
        self.back_booking.setGeometry(QtCore.QRect(20, 10, 41, 28))
        self.back_booking.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.back_booking.setObjectName("back_booking")
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.addWidget(self.scrollArea_3)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.quizpage = QtWidgets.QFrame(self.page_10)
        self.quizpage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quizpage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quizpage.setObjectName("quizpage")
        self.horizontalLayout_9.addWidget(self.quizpage)
        self.stackedWidget.addWidget(self.page_10)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.profile_btn_1.toggled['bool'].connect(self.profile_btn_2.setChecked) # type: ignore
        self.history_btn_1.toggled['bool'].connect(self.history_btn_2.setChecked) # type: ignore
        self.booking_btn_1.toggled['bool'].connect(self.booking_btn_2.setChecked) # type: ignore
        self.profile_btn_2.toggled['bool'].connect(self.profile_btn_1.setChecked) # type: ignore
        self.history_btn_2.toggled['bool'].connect(self.history_btn_1.setChecked) # type: ignore
        self.booking_btn_2.toggled['bool'].connect(self.booking_btn_1.setChecked) # type: ignore
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.exit_btn_1.clicked.connect(MainWindow.close) # type: ignore
        self.deals_btn_1.toggled['bool'].connect(self.deal_btn_2.setChecked) # type: ignore
        self.chatbot_btn_1.toggled['bool'].connect(self.chatbot_btn_2.setChecked) # type: ignore
        self.feedback_btn_1.toggled['bool'].connect(self.feedback_btn_2.setChecked) # type: ignore
        self.deal_btn_2.toggled['bool'].connect(self.deals_btn_1.setChecked) # type: ignore
        self.chatbot_btn_2.toggled['bool'].connect(self.chatbot_btn_1.setChecked) # type: ignore
        self.feedback_btn_2.toggled['bool'].connect(self.feedback_btn_1.setChecked) # type: ignore
        self.map_btn_2.toggled['bool'].connect(self.map_btn_1.setChecked) # type: ignore
        self.map_btn_1.toggled['bool'].connect(self.map_btn_2.setChecked) # type: ignore
        self.quiz_btn_2.toggled['bool'].connect(self.quiz_btn_1.setChecked) # type: ignore
        self.quiz_btn_1.toggled['bool'].connect(self.quiz_btn_2.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.fetch_and_populate_data()
        self.history_btn_2.clicked.connect(self.show_booking_data)

        button_size = QtCore.QSize(120, 50)  # Adjust the width and height as needed

        self.attraction_btn_2.setFixedSize(button_size)
        self.profile_btn_2.setFixedSize(button_size)
        self.history_btn_2.setFixedSize(button_size)
        self.booking_btn_2.setFixedSize(button_size)
        self.deal_btn_2.setFixedSize(button_size)
        self.chatbot_btn_2.setFixedSize(button_size)
        self.feedback_btn_2.setFixedSize(button_size)
        self.map_btn_2.setFixedSize(button_size)
        self.quiz_btn_2.setFixedSize(button_size)

        button_size_1 = QtCore.QSize(75, 50)  # Adjust the width and height as needed

        self.attraction_btn_1.setFixedSize(button_size_1)
        self.profile_btn_1.setFixedSize(button_size_1)
        self.history_btn_1.setFixedSize(button_size_1)
        self.booking_btn_1.setFixedSize(button_size_1)
        self.deals_btn_1.setFixedSize(button_size_1)
        self.chatbot_btn_1.setFixedSize(button_size_1)
        self.feedback_btn_1.setFixedSize(button_size_1)
        self.map_btn_1.setFixedSize(button_size_1)
        self.quiz_btn_1.setFixedSize(button_size_1)

        # Create a QCalendarWidget instance for checkin and checkout
        self.checkin_calendar = QtWidgets.QCalendarWidget()
        self.checkin_calendar.setWindowFlags(QtCore.Qt.Popup)
        self.checkin_calendar.setGridVisible(True)
        self.checkout_calendar = QtWidgets.QCalendarWidget()
        self.checkout_calendar.setWindowFlags(QtCore.Qt.Popup)
        self.checkout_calendar.setGridVisible(True)

        # Connect the show_calendar functions to the input fields
        self.checkin_input_2.mousePressEvent = self.show_checkin_calendar_2
        self.checkout_input_2.mousePressEvent = self.show_checkout_calendar_2

        # Create a slot function for the booking button
        def book_success():
            selected_number = self.comboBox.currentText()
            QtWidgets.QMessageBox.information(MainWindow, "Booking Successful",
                                              f"{selected_number} has been booked successfully.")
            flow = InstalledAppFlow.from_client_secrets_file(
                r"C:\Users\See Jia Wei\OneDrive\Documents\ALL2\client_secret_379816141851-frjap9raqtnjcn5t8t97v51vmum6te8e.apps.googleusercontent.com.json",
                SCOPES)
            credentials = flow.run_local_server(port=0)

            def create_message(sender, to, subject, message_text):
                message = MIMEText(message_text)
                message['to'] = to
                message['subject'] = subject
                return {'raw': base64.urlsafe_b64encode(message.as_bytes()).decode()}

            def send_message(service, user_id, message):
                try:
                    message = service.users().messages().send(userId=user_id, body=message).execute()
                    print(f"Message sent. Message Id: {message['id']}")
                except Exception as e:
                    print(f"An error occurred: {e}")

            service = build('gmail', 'v1', credentials=credentials)
            subject = 'Hello from your PyQt5 app'
            message_text = 'This is a test email sent from a PyQt5 application.'

            send_message(service, 'me', create_message('me', 'usermapping1@gmail.com', subject, message_text))

        # Connect the booking button to the book_success function
        self.booking_btn.clicked.connect(book_success)


    def fetch_data(self):
        try:
            # Connect to the MySQL database
            db_connection = mysql.connector.connect(
                host="localhost",
                user="root",
                password="desmond1234",
                database="tourism information kiosk"
            )
            cursor = db_connection.cursor()

            # Define your SQL query to fetch data and images by performing a JOIN
            sql_query = """
            SELECT a.attractions_name, a.attractions_price, a.description, a.attractions_address, i.image_data
            FROM attractions AS a
            LEFT JOIN image AS i ON a.attractions_id = i.attractions_id
            """
            cursor.execute(sql_query)
            data = cursor.fetchall()

            # Close the cursor and database connection
            cursor.close()
            db_connection.close()
            return data

        except mysql.connector.Error as err:
            print(f"Error fetching data from the database: {err}")
        return None

    def fetch_and_populate_data(self):
        data = self.fetch_data()

        if data:
            for index, (attraction_name, attractions_price, description, attractions_address,image_data) in enumerate(data):
                new_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
                new_frame.setFixedSize(1200, 500)
                new_frame.setFrameShape(QtWidgets.QFrame.Box)
                new_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_6.setSpacing(0)
                self.verticalLayout_6.insertWidget(0, new_frame)
                image_label = QtWidgets.QLabel(new_frame)
                image_label.setGeometry(QtCore.QRect(30, 40, 441, 391))  # Adjust the position and size as needed
                # Set the image data here (assuming the image_data is a binary image)
                # For example, you can use QPixmap to display the image:
                pixmap = QtGui.QPixmap()
                pixmap.loadFromData(image_data)
                image_label.setPixmap(pixmap)

                name_text_edit = QtWidgets.QTextEdit(new_frame)
                name_text_edit.setGeometry(QtCore.QRect(520, 50, 501, 51))

                # Set the entire text as HTML with bold formatting
                name_text_edit.setHtml(f'<b>Name: {attraction_name}</b>')
                name_text_edit.setObjectName(f"name{index + 1}")

                # Set the QTextEdit field as read-only
                name_text_edit.setReadOnly(True)

                price_text_edit = QtWidgets.QTextEdit(new_frame)
                price_text_edit.setGeometry(QtCore.QRect(1060, 50, 104, 51))

                # Set the entire text as HTML with bold formatting
                price_text_edit.setHtml(f'<b>RM {attractions_price}</b>')
                price_text_edit.setObjectName(f"price{index + 1}")

                # Set the QTextEdit field as read-only
                price_text_edit.setReadOnly(True)

                description_text_edit = QtWidgets.QTextEdit(new_frame)
                description_text_edit.setGeometry(QtCore.QRect(520, 150, 631, 101))
                description_text_edit.setPlainText(description)
                description_text_edit.setHtml(f'<b><u>Description</u></b><br>{description}')
                description_text_edit.setObjectName(f"description{index + 1}")

                # Set the QTextEdit field as read-only
                description_text_edit.setReadOnly(True)

                address_text_edit = QtWidgets.QTextEdit(new_frame)
                address_text_edit.setGeometry(QtCore.QRect(520, 300, 631, 101))
                address_text_edit.setPlainText(attractions_address)
                address_text_edit.setHtml(f'<b><u>Address</u></b><br>{attractions_address}')
                address_text_edit.setObjectName(f"address{index + 1}")

                # Set the QTextEdit field as read-only
                address_text_edit.setReadOnly(True)

                font = QtGui.QFont()
                font.setPointSize(10)

                # Apply the font to the QTextEdit widgets
                name_text_edit.setFont(font)
                price_text_edit.setFont(font)
                address_text_edit.setFont(font)
                description_text_edit.setFont(font)

                self.verticalLayout_10.addWidget(new_frame)

    def show_booking_data(self):
        # Call the method to fetch and populate data
        self.fetch_and_populate_booking_data()

        # Make the frame visible
        self.frame.setVisible(True)

    def fetch_deals_data(self):
        try:
            # Connect to the MySQL database
            db_connection = mysql.connector.connect(
                host="localhost",
                user="root",
                password="desmond1234",
                database="tourism information kiosk"
            )
            cursor = db_connection.cursor()

            # Define your SQL query to fetch data and images by performing a JOIN
            sql_query = """
            SELECT d.deals_name, d.deals_description, d.discount, d.promocode,d.attractions_id, i.image_data
            FROM deals AS d
            LEFT JOIN image AS i ON d.attractions_id = i.attractions_id
            """
            cursor.execute(sql_query)
            data = cursor.fetchall()

            # Close the cursor and database connection
            cursor.close()
            db_connection.close()
            return data

        except mysql.connector.Error as err:
            print(f"Error fetching data from the database: {err}")
        return None

    def fetch_and_populate_deals_data(self):
        data = self.fetch_deals_data()

        if data:
            for index, (deals_name, deals_description, discount, promocode, attractions_id, image_data) in enumerate(
                    data):
                new_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
                new_frame.setFixedSize(1200, 500)
                new_frame.setFrameShape(QtWidgets.QFrame.Box)
                new_frame.setFrameShadow(QtWidgets.QFrame.Raised)

                # Create a new vertical layout for each frame
                new_frame_layout = QtWidgets.QVBoxLayout(new_frame)
                new_frame.setLayout(new_frame_layout)

                # Image Label
                image_label = QtWidgets.QLabel(new_frame)
                image_label.setGeometry(QtCore.QRect(30, 40, 441, 391))  # Adjust the position and size as needed
                pixmap = QtGui.QPixmap()

                if pixmap.loadFromData(image_data):
                    image_label.setPixmap(pixmap)
                    image_label.setScaledContents(True)
                else:
                    print("Failed to load image data.")

                # Deals Name Text Edit
                deals_name_text_edit = QtWidgets.QTextEdit(new_frame)
                deals_name_text_edit.setGeometry(QtCore.QRect(480, 40, 561, 61))
                deals_name_text_edit.setPlainText(deals_name)
                deals_name_text_edit.setHtml(f'<b>Name:{deals_name}</b>')
                deals_name_text_edit.setObjectName(f"deals_name{index + 1}")

                # Deals Price Text Edit
                deals_price_text_edit = QtWidgets.QTextEdit(new_frame)
                deals_price_text_edit.setGeometry(QtCore.QRect(1070, 40, 111, 61))
                deals_price_text_edit.setPlainText(str(discount))
                deals_price_text_edit.setHtml(f'<b>Discount: {discount}</b>')
                deals_price_text_edit.setObjectName(f"discount{index + 1}")

                # Deals Description Text Edit
                deals_description_text_edit = QtWidgets.QTextEdit(new_frame)
                deals_description_text_edit.setGeometry(QtCore.QRect(480, 110, 701, 151))
                deals_description_text_edit.setPlainText(deals_description)
                deals_description_text_edit.setHtml(f'<b>Descriptions: </b>{deals_description}')
                deals_description_text_edit.setObjectName(f"deals_description{index + 1}")

                # Deals Promocode Text Edit
                deals_promocode_text_edit = QtWidgets.QTextEdit(new_frame)
                deals_promocode_text_edit.setGeometry(QtCore.QRect(480, 270, 701, 161))
                deals_promocode_text_edit.setPlainText(promocode)
                deals_promocode_text_edit.setHtml(f'<b>Promocode:</b>{promocode}')
                deals_promocode_text_edit.setObjectName(f"promocode{index + 1}")

                image_label.setVisible(True)
                deals_name_text_edit.setVisible(True)
                deals_description_text_edit.setVisible(True)
                deals_promocode_text_edit.setVisible(True)

                # Set the QTextEdit fields as read-only
                deals_name_text_edit.setReadOnly(True)
                deals_price_text_edit.setReadOnly(True)
                deals_description_text_edit.setReadOnly(True)
                deals_promocode_text_edit.setReadOnly(True)

                font = QtGui.QFont()
                font.setPointSize(10)

                deals_name_text_edit.setFont(font)
                deals_price_text_edit.setFont(font)
                deals_description_text_edit.setFont(font)
                deals_promocode_text_edit.setFont(font)

                # Add the new frame to the main layout
                self.verticalLayout_8.addWidget(new_frame)

    def fetch_booking_data_from_database(self):
        # Connect to the MySQL database
        db_connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="desmond1234",
            database="tourism information kiosk"
        )
        cursor = db_connection.cursor()

        # Define your SQL query to fetch data from the database by performing a JOIN
        sql_query = """
        SELECT
    b.booking_id,
    b.booking_date,
    b.booking_days,
    b.status,
    a.attractions_name,
    a.attractions_price,
    c.quantities,
    a.attractions_price * c.quantities AS total_amount
FROM
    booking AS b
LEFT JOIN booking_details AS c ON b.booking_id = c.booking_id
LEFT JOIN attractions AS a ON c.attractions_id = a.attractions_id;

        """
        cursor.execute(sql_query)
        data = cursor.fetchall()

        # Close the cursor and database connection
        cursor.close()
        db_connection.close()

        return data

    def show_booking_data(self):
        data = self.fetch_booking_data_from_database()

        if data:
            for row in data:
                item = QtWidgets.QTreeWidgetItem(self.treeWidget)

                # Set the text for each column based on your desired mapping
                item.setText(0, str(row[0]))  # Booking ID
                item.setText(1, str(row[4]))  # Attraction Name
                item.setText(2, str(row[1]))  # Booking Date
                item.setText(3, str(row[2]))  # Booking Days
                item.setText(4, str(row[6]))  # Quantities
                item.setText(5, str(row[5]))  # Attraction Price
                item.setText(6, str(row[7]))  # Total Amount
                item.setText(7, str(row[3]))  # Status

                # Add the item to the treeWidget
                self.treeWidget.addTopLevelItem(item)

    def show_checkin_calendar_2(self, event):
        try:
            print("show_checkin_calendar_2 called")
            pos = self.checkin_input_2.mapToGlobal(QtCore.QPoint(0, self.checkin_input_2.height()))
            self.checkin_calendar.setMinimumDate(QtCore.QDate.currentDate())
            self.checkin_calendar.setSelectedDate(self.checkin_input_2.date())
            self.checkin_calendar.move(pos)
            self.checkin_calendar.show()

            existing_connections = self.checkin_calendar.receivers(self.checkin_calendar.clicked)
            if existing_connections > 0:
                self.checkin_calendar.clicked.disconnect()
            self.checkin_calendar.clicked.connect(
                lambda: self.update_checkin_input_2(self.checkin_calendar.selectedDate()))
        except Exception as e:
            print(f"Error in show_checkin_calendar_2: {e}")

    def update_checkin_input_2(self, date):
        self.checkin_input_2.setDate(self.checkin_calendar.selectedDate())
        self.checkin_calendar.hide()

    def show_checkout_calendar_2(self, event):
        try:
            print("show_checkout_calendar_2 called")
            pos = self.checkout_input_2.mapToGlobal(QtCore.QPoint(0, self.checkout_input_2.height()))
            self.checkout_calendar.setMinimumDate(self.checkin_input_2.date())
            self.checkout_calendar.setSelectedDate(self.checkout_input_2.date())
            self.checkout_calendar.move(pos)
            self.checkout_calendar.show()

            existing_connections = self.checkout_calendar.receivers(self.checkout_calendar.clicked)
            if existing_connections > 0:
                self.checkout_calendar.clicked.disconnect()
            self.checkout_calendar.clicked.connect(
                lambda: self.update_checkout_input_2(self.checkout_calendar.selectedDate()))
        except Exception as e:
            print(f"Error in show_checkout_calendar_2: {e}")
    def update_checkout_input_2(self, date):
        self.checkout_input_2.setDate(self.checkout_calendar.selectedDate())
        self.checkout_calendar.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.attraction_btn_2.setText(_translate("MainWindow", "Attraction"))
        self.profile_btn_2.setText(_translate("MainWindow", "Profile"))
        self.history_btn_2.setText(_translate("MainWindow", "History"))
        self.booking_btn_2.setText(_translate("MainWindow", "Booking"))
        self.deal_btn_2.setText(_translate("MainWindow", "Deals"))
        self.chatbot_btn_2.setText(_translate("MainWindow", "ChatBot"))
        self.feedback_btn_2.setText(_translate("MainWindow", "Feedback"))
        self.map_btn_2.setText(_translate("MainWindow", "Map"))
        self.quiz_btn_2.setText(_translate("MainWindow", "Quiz"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
        self.username.setText(_translate("MainWindow", "User Name"))
        self.ProfileSetting.setText(_translate("MainWindow", "Profile Setting "))
        self.FirstName_input.setPlaceholderText(_translate("MainWindow", "first name"))
        self.LastName_input.setPlaceholderText(_translate("MainWindow", "surname"))
        self.MobileNumber_input.setPlaceholderText(_translate("MainWindow", "enter phone number"))
        self.Address1_input.setPlaceholderText(_translate("MainWindow", "enter address "))
        self.postcode_input.setPlaceholderText(_translate("MainWindow", "enter address line 3"))
        self.Area_input.setPlaceholderText(_translate("MainWindow", "enter address line 4"))
        self.FirstName.setText(_translate("MainWindow", "First Name"))
        self.LastName.setText(_translate("MainWindow", "Last Name"))
        self.MobileNumber.setText(_translate("MainWindow", "Mobile Number"))
        self.Address.setText(_translate("MainWindow", "Address "))
        self.Postcode.setText(_translate("MainWindow", "Postcode"))
        self.Area.setText(_translate("MainWindow", "Area"))
        self.save_profile_button.setText(_translate("MainWindow", "save profile"))
        self.DateOfBirth.setText(_translate("MainWindow", "Date Of Birth"))
        self.Gender.setText(_translate("MainWindow", "Gender"))
        self.male_checkBox.setText(_translate("MainWindow", "Male"))
        self.female_checkBox.setText(_translate("MainWindow", "Female"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "BookingID"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Venue"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Date"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Days"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Quantities"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "Amount per ticket"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "Total Amount"))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "Status"))
        self.history_label.setText(_translate("MainWindow", "Booking History"))


        self.book_btn.setText(_translate("MainWindow", "Book Now >"))
        self.bookingtitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.booking_price.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">RM</span></p></body></html>"))
        self.bookingtitle_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.bookingtitle_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.bookingtitle_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.bookingtitle_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.book_btn_2.setText(_translate("MainWindow", "Book Now >"))
        self.book_btn_3.setText(_translate("MainWindow", "Book Now >"))
        self.book_btn_4.setText(_translate("MainWindow", "Book Now >"))
        self.book_btn_5.setText(_translate("MainWindow", "Book Now >"))
        self.booking_price_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">RM</span></p></body></html>"))
        self.booking_price_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">RM</span></p></body></html>"))
        self.booking_price_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">RM</span></p></body></html>"))
        self.booking_price_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">RM</span></p></body></html>"))
        self.customerservicepage.setText(_translate("MainWindow", "Customer Service"))
        self.feedbackpage.setText(_translate("MainWindow", "Feedback"))

        self.booking_title_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Name:</span></p></body></html>"))
        self.booking_price_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">RM:</span></p></body></html>"))
        self.booking_btn.setText(_translate("MainWindow", "BOOK"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "12"))
        self.comboBox.setItemText(11, _translate("MainWindow", "13"))
        self.comboBox.setItemText(12, _translate("MainWindow", "14"))
        self.comboBox.setItemText(13, _translate("MainWindow", "15"))
        self.comboBox.setItemText(14, _translate("MainWindow", "16"))
        self.comboBox.setItemText(15, _translate("MainWindow", "17"))
        self.comboBox.setItemText(16, _translate("MainWindow", "18"))
        self.comboBox.setItemText(17, _translate("MainWindow", "19"))
        self.comboBox.setItemText(18, _translate("MainWindow", "20"))
        self.back_booking.setText(_translate("MainWindow", "BACK"))

        # Load icons for checked and unchecked states
        self.change_btn_unchecked_icon = QtGui.QIcon(QtGui.QPixmap("navigationmanual.png"))
        self.change_btn_checked_icon = QtGui.QIcon(QtGui.QPixmap("back.png"))

        # Create a slot method to update the change_btn icon
        def update_change_btn_icon(checked):
            if checked:
                self.change_btn.setIcon(self.change_btn_unchecked_icon)
            else:
                self.change_btn.setIcon(self.change_btn_checked_icon)

        # Connect the change_btn's toggled signal to the slot method
        self.change_btn.toggled.connect(update_change_btn_icon)

        # Create a slot function for saving the user's profile
        def save_profile(user_name):
            print("Inside save_profile function")
            # Retrieve user input from the input fields
            first_name = self.FirstName_input.text()
            last_name = self.LastName_input.text()
            mobile_number = self.MobileNumber_input.text()
            address1 = self.Address1_input.text()
            postcode = self.postcode_input.text()
            area = self.Area_input.text()
            user_name = entered_username

            try:
                # Connect to the MySQL database
                db_connection = mysql.connector.connect(
                    host="localhost",
                    user="root",
                    password="desmond1234",
                    database="tourism information kiosk"
                )

                cursor = db_connection.cursor()

                # Perform validation (you can add more validation logic)
                if not first_name or not last_name:
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error",
                                                  "First name and last name are required.")
                    return

                if not mobile_number:
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error", "Mobile number is required.")
                    return
                if not address1:
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error", "Address is required.")
                    return
                if not postcode:
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error", "Postcode is required.")
                    return
                if not area:
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error", "Area is required.")
                    return

                # Additional validation for mobile number (you can customize this)
                if not mobile_number.isdigit():
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error", "Mobile number must be a number.")
                    return
                if len(mobile_number) < 10 or len(mobile_number) > 12:
                    QtWidgets.QMessageBox.warning(self.page_1, "Validation Error", "Mobile number must be valid.")
                    return

                insert_query = "INSERT INTO user ( user_name, first_name, last_name, contact_number, address, postcode, area) VALUES (  %s, %s, %s, %s, %s, %s)"
                cursor.execute(insert_query,
                               (user_name, first_name, last_name, mobile_number, address1, postcode, area))
                db_connection.commit()
                cursor.close()
                # Display a success message
                QtWidgets.QMessageBox.information(self.page_1, "Profile Saved", "Your profile has been saved.")
            except mysql.connector.Error as err:
                QtWidgets.QMessageBox.warning(self.page_1, "Database Error", f"Error saving profile data: {err}")

        # Connect the "Save" button to the save_profile function with the entered username
        self.save_profile_button.clicked.connect(lambda: save_profile(entered_username))

        self.deal_btn_2.clicked.connect(self.fetch_and_populate_deals_data)




import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
